"""reconcile current application schema

Revision ID: 20261003_0006
Revises: 20261003_0005
Create Date: 2026-10-03 21:40:24.358629
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '20261003_0006'
down_revision = '20261003_0005'
branch_labels = None
depends_on = None


APPLICATION_TABLES = (
    "agent_feedback_events", "agent_runs", "agent_steps", "ai_memory_brain",
    "analytics_events", "api_usage_logs", "app_settings", "admin_activity_logs",
    "chat_messages", "chat_sessions", "comments", "company_budgets",
    "contact_submissions", "contacts", "content_submissions", "controllers",
    "dashboard_metrics", "document_embeddings", "email_templates",
    "estimation_history", "expense_categories", "feed_sources",
    "intelligence_sources", "logistics_estimates", "payment_history", "posts",
    "project_revenues", "scheduled_workflow_jobs", "subscribers", "subscriptions",
    "vehicle_types", "workflow_nodes", "workflow_runs", "workflows",
)


def _table_names() -> set[str]:
    bind = op.get_bind()
    schema = "public" if bind.dialect.name == "postgresql" else None
    return set(sa.inspect(bind).get_table_names(schema=schema))


def _column_names(table: str) -> set[str]:
    bind = op.get_bind()
    schema = "public" if bind.dialect.name == "postgresql" else None
    return {column["name"] for column in sa.inspect(bind).get_columns(table, schema=schema)}


def _index_names(table: str) -> set[str]:
    bind = op.get_bind()
    schema = "public" if bind.dialect.name == "postgresql" else None
    return {index["name"] for index in sa.inspect(bind).get_indexes(table, schema=schema)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if "agent_feedback_events" not in _table_names():
        op.create_table('agent_feedback_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_agent_feedback_events_created_at" not in _index_names("agent_feedback_events"):
        op.create_index(op.f('ix_agent_feedback_events_created_at'), 'agent_feedback_events', ['created_at'], unique=False)
    if "ix_agent_feedback_events_id" not in _index_names("agent_feedback_events"):
        op.create_index(op.f('ix_agent_feedback_events_id'), 'agent_feedback_events', ['id'], unique=False)
    if "ix_agent_feedback_events_run_id" not in _index_names("agent_feedback_events"):
        op.create_index(op.f('ix_agent_feedback_events_run_id'), 'agent_feedback_events', ['run_id'], unique=False)
    if "api_usage_logs" not in _table_names():
        op.create_table('api_usage_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=120), nullable=False),
        sa.Column('api_key_name', sa.String(length=255), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('model', sa.String(length=255), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_api_usage_logs_created_at" not in _index_names("api_usage_logs"):
        op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    if "ix_api_usage_logs_id" not in _index_names("api_usage_logs"):
        op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    if "ix_api_usage_logs_model" not in _index_names("api_usage_logs"):
        op.create_index(op.f('ix_api_usage_logs_model'), 'api_usage_logs', ['model'], unique=False)
    if "ix_api_usage_logs_provider" not in _index_names("api_usage_logs"):
        op.create_index(op.f('ix_api_usage_logs_provider'), 'api_usage_logs', ['provider'], unique=False)
    if "ix_api_usage_logs_role" not in _index_names("api_usage_logs"):
        op.create_index(op.f('ix_api_usage_logs_role'), 'api_usage_logs', ['role'], unique=False)
    if "chat_sessions" not in _table_names():
        op.create_table('chat_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('agent_id', sa.String(length=100), nullable=True),
        sa.Column('context', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_chat_sessions_id" not in _index_names("chat_sessions"):
        op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    if "ix_chat_sessions_owner_id" not in _index_names("chat_sessions"):
        op.create_index(op.f('ix_chat_sessions_owner_id'), 'chat_sessions', ['owner_id'], unique=False)
    if "ix_chat_sessions_session_id" not in _index_names("chat_sessions"):
        op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    if "company_budgets" not in _table_names():
        op.create_table('company_budgets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('total_budget', sa.Float(), nullable=False),
        sa.Column('spent_amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_company_budgets_id" not in _index_names("company_budgets"):
        op.create_index(op.f('ix_company_budgets_id'), 'company_budgets', ['id'], unique=False)
    if "ix_company_budgets_updated_at" not in _index_names("company_budgets"):
        op.create_index(op.f('ix_company_budgets_updated_at'), 'company_budgets', ['updated_at'], unique=False)
    if "content_submissions" not in _table_names():
        op.create_table('content_submissions',
        sa.Column('id', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('subject', sa.String(length=500), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_content_submissions_email" not in _index_names("content_submissions"):
        op.create_index(op.f('ix_content_submissions_email'), 'content_submissions', ['email'], unique=False)
    if "ix_content_submissions_id" not in _index_names("content_submissions"):
        op.create_index(op.f('ix_content_submissions_id'), 'content_submissions', ['id'], unique=False)
    if "ix_content_submissions_status" not in _index_names("content_submissions"):
        op.create_index(op.f('ix_content_submissions_status'), 'content_submissions', ['status'], unique=False)
    if "controllers" not in _table_names():
        op.create_table('controllers',
        sa.Column('id', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('trigger_type', sa.String(length=100), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('config', sa.Text(), nullable=True),
        sa.Column('last_execution', sa.DateTime(timezone=True), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=False),
        sa.Column('failure_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_controllers_enabled" not in _index_names("controllers"):
        op.create_index(op.f('ix_controllers_enabled'), 'controllers', ['enabled'], unique=False)
    if "ix_controllers_id" not in _index_names("controllers"):
        op.create_index(op.f('ix_controllers_id'), 'controllers', ['id'], unique=False)
    if "ix_controllers_name" not in _index_names("controllers"):
        op.create_index(op.f('ix_controllers_name'), 'controllers', ['name'], unique=False)
    if "email_templates" not in _table_names():
        op.create_table('email_templates',
        sa.Column('id', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('subject', sa.String(length=500), nullable=False),
        sa.Column('template_html', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_email_templates_id" not in _index_names("email_templates"):
        op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    if "ix_email_templates_is_active" not in _index_names("email_templates"):
        op.create_index(op.f('ix_email_templates_is_active'), 'email_templates', ['is_active'], unique=False)
    if "ix_email_templates_name" not in _index_names("email_templates"):
        op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=False)
    if "expense_categories" not in _table_names():
        op.create_table('expense_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('budget', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_expense_categories_id" not in _index_names("expense_categories"):
        op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    if "ix_expense_categories_name" not in _index_names("expense_categories"):
        op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=True)
    if "feed_sources" not in _table_names():
        op.create_table('feed_sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=1000), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=80), nullable=False),
        sa.Column('trust_level', sa.String(length=40), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_scrape_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_scrape_status', sa.String(length=40), nullable=False),
        sa.Column('scrape_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_feed_sources_category" not in _index_names("feed_sources"):
        op.create_index(op.f('ix_feed_sources_category'), 'feed_sources', ['category'], unique=False)
    if "ix_feed_sources_id" not in _index_names("feed_sources"):
        op.create_index(op.f('ix_feed_sources_id'), 'feed_sources', ['id'], unique=False)
    if "ix_feed_sources_is_active" not in _index_names("feed_sources"):
        op.create_index(op.f('ix_feed_sources_is_active'), 'feed_sources', ['is_active'], unique=False)
    if "ix_feed_sources_url" not in _index_names("feed_sources"):
        op.create_index(op.f('ix_feed_sources_url'), 'feed_sources', ['url'], unique=True)
    if "project_revenues" not in _table_names():
        op.create_table('project_revenues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('estimated_revenue', sa.Float(), nullable=False),
        sa.Column('estimated_cost', sa.Float(), nullable=False),
        sa.Column('actual_revenue', sa.Float(), nullable=False),
        sa.Column('actual_cost', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_project_revenues_created_at" not in _index_names("project_revenues"):
        op.create_index(op.f('ix_project_revenues_created_at'), 'project_revenues', ['created_at'], unique=False)
    if "ix_project_revenues_id" not in _index_names("project_revenues"):
        op.create_index(op.f('ix_project_revenues_id'), 'project_revenues', ['id'], unique=False)
    if "ix_project_revenues_name" not in _index_names("project_revenues"):
        op.create_index(op.f('ix_project_revenues_name'), 'project_revenues', ['name'], unique=False)
    if "ix_project_revenues_status" not in _index_names("project_revenues"):
        op.create_index(op.f('ix_project_revenues_status'), 'project_revenues', ['status'], unique=False)
    if "vehicle_types" not in _table_names():
        op.create_table('vehicle_types',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('length_cm', sa.Float(), nullable=False),
        sa.Column('width_cm', sa.Float(), nullable=False),
        sa.Column('height_cm', sa.Float(), nullable=False),
        sa.Column('max_weight_kg', sa.Float(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_vehicle_types_id" not in _index_names("vehicle_types"):
        op.create_index(op.f('ix_vehicle_types_id'), 'vehicle_types', ['id'], unique=False)
    if "workflows" not in _table_names():
        op.create_table('workflows',
        sa.Column('id', sa.String(length=80), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_workflows_id" not in _index_names("workflows"):
        op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    if "ix_workflows_name" not in _index_names("workflows"):
        op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    if "chat_messages" not in _table_names():
        op.create_table('chat_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('agent_id', sa.String(length=100), nullable=True),
        sa.Column('model_used', sa.String(length=100), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('cost_estimate', sa.Float(), nullable=True),
        sa.Column('json_metadata', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_chat_messages_created_at" not in _index_names("chat_messages"):
        op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    if "ix_chat_messages_id" not in _index_names("chat_messages"):
        op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    if "ix_chat_messages_session_id" not in _index_names("chat_messages"):
        op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    if "comments" not in _table_names():
        op.create_table('comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('toxicity_score', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('likes', sa.Integer(), nullable=True),
        sa.Column('dislikes', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_comments_id" not in _index_names("comments"):
        op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    if "ix_comments_parent_id" not in _index_names("comments"):
        op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    if "ix_comments_post_id" not in _index_names("comments"):
        op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    if "ix_comments_status" not in _index_names("comments"):
        op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    if "ix_comments_user_id" not in _index_names("comments"):
        op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    if "logistics_estimates" not in _table_names():
        op.create_table('logistics_estimates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.String(length=50), nullable=False),
        sa.Column('carton_length_cm', sa.Float(), nullable=False),
        sa.Column('carton_width_cm', sa.Float(), nullable=False),
        sa.Column('carton_height_cm', sa.Float(), nullable=False),
        sa.Column('carton_weight_kg', sa.Float(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('vehicle_length_cm', sa.Float(), nullable=False),
        sa.Column('vehicle_width_cm', sa.Float(), nullable=False),
        sa.Column('vehicle_height_cm', sa.Float(), nullable=False),
        sa.Column('vehicle_max_weight_kg', sa.Float(), nullable=False),
        sa.Column('estimated_capacity_percent', sa.Float(), nullable=False),
        sa.Column('estimated_weight_percent', sa.Float(), nullable=False),
        sa.Column('can_fit_by_volume', sa.Boolean(), nullable=False),
        sa.Column('can_fit_by_weight', sa.Boolean(), nullable=False),
        sa.Column('total_estimates', sa.Integer(), nullable=False),
        sa.Column('total_volume_cm3', sa.Float(), nullable=False),
        sa.Column('total_weight_kg', sa.Float(), nullable=False),
        sa.Column('vehicle_volume_cm3', sa.Float(), nullable=False),
        sa.Column('user_ip', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_types.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_logistics_estimates_id" not in _index_names("logistics_estimates"):
        op.create_index(op.f('ix_logistics_estimates_id'), 'logistics_estimates', ['id'], unique=False)
    if "ix_logistics_estimates_vehicle_id" not in _index_names("logistics_estimates"):
        op.create_index(op.f('ix_logistics_estimates_vehicle_id'), 'logistics_estimates', ['vehicle_id'], unique=False)
    if "workflow_nodes" not in _table_names():
        op.create_table('workflow_nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.String(length=80), nullable=False),
        sa.Column('node_id', sa.String(length=80), nullable=False),
        sa.Column('node_type', sa.String(length=40), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('depends_on', sa.Text(), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('timeout_seconds', sa.Integer(), nullable=False),
        sa.Column('config', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_workflow_nodes_id" not in _index_names("workflow_nodes"):
        op.create_index(op.f('ix_workflow_nodes_id'), 'workflow_nodes', ['id'], unique=False)
    if "ix_workflow_nodes_node_id" not in _index_names("workflow_nodes"):
        op.create_index(op.f('ix_workflow_nodes_node_id'), 'workflow_nodes', ['node_id'], unique=False)
    if "ix_workflow_nodes_workflow_id" not in _index_names("workflow_nodes"):
        op.create_index(op.f('ix_workflow_nodes_workflow_id'), 'workflow_nodes', ['workflow_id'], unique=False)
    if "workflow_runs" not in _table_names():
        op.create_table('workflow_runs',
        sa.Column('id', sa.String(length=80), nullable=False),
        sa.Column('workflow_id', sa.String(length=80), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('current_node', sa.String(length=80), nullable=True),
        sa.Column('completed_nodes', sa.Text(), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('execution_log', sa.Text(), nullable=False),
        sa.Column('metrics_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_workflow_runs_id" not in _index_names("workflow_runs"):
        op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    if "ix_workflow_runs_status" not in _index_names("workflow_runs"):
        op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    if "ix_workflow_runs_workflow_id" not in _index_names("workflow_runs"):
        op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    if "estimation_history" not in _table_names():
        op.create_table('estimation_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('estimate_id', sa.Integer(), nullable=False),
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('json_metadata', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['estimate_id'], ['logistics_estimates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_estimation_history_estimate_id" not in _index_names("estimation_history"):
        op.create_index(op.f('ix_estimation_history_estimate_id'), 'estimation_history', ['estimate_id'], unique=False)
    if "ix_estimation_history_id" not in _index_names("estimation_history"):
        op.create_index(op.f('ix_estimation_history_id'), 'estimation_history', ['id'], unique=False)
    if "scheduled_workflow_jobs" not in _table_names():
        op.create_table('scheduled_workflow_jobs',
        sa.Column('id', sa.String(length=80), nullable=False),
        sa.Column('run_id', sa.String(length=80), nullable=False),
        sa.Column('workflow_id', sa.String(length=80), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "ix_scheduled_workflow_jobs_id" not in _index_names("scheduled_workflow_jobs"):
        op.create_index(op.f('ix_scheduled_workflow_jobs_id'), 'scheduled_workflow_jobs', ['id'], unique=False)
    if "ix_scheduled_workflow_jobs_run_id" not in _index_names("scheduled_workflow_jobs"):
        op.create_index(op.f('ix_scheduled_workflow_jobs_run_id'), 'scheduled_workflow_jobs', ['run_id'], unique=True)
    if "ix_scheduled_workflow_jobs_scheduled_for" not in _index_names("scheduled_workflow_jobs"):
        op.create_index(op.f('ix_scheduled_workflow_jobs_scheduled_for'), 'scheduled_workflow_jobs', ['scheduled_for'], unique=False)
    if "ix_scheduled_workflow_jobs_status" not in _index_names("scheduled_workflow_jobs"):
        op.create_index(op.f('ix_scheduled_workflow_jobs_status'), 'scheduled_workflow_jobs', ['status'], unique=False)
    if "ix_scheduled_workflow_jobs_workflow_id" not in _index_names("scheduled_workflow_jobs"):
        op.create_index(op.f('ix_scheduled_workflow_jobs_workflow_id'), 'scheduled_workflow_jobs', ['workflow_id'], unique=False)
    if "provider" not in _column_names("agent_runs"):
        op.add_column('agent_runs', sa.Column('provider', sa.String(length=120), nullable=True))
    if "input_context" not in _column_names("agent_runs"):
        op.add_column('agent_runs', sa.Column('input_context', sa.Text(), nullable=False, server_default=sa.text("'{}'")))
    if "source_ids" not in _column_names("agent_runs"):
        op.add_column('agent_runs', sa.Column('source_ids', sa.Text(), nullable=False, server_default=sa.text("'[]'")))
    if "token_usage" not in _column_names("agent_runs"):
        op.add_column('agent_runs', sa.Column('token_usage', sa.Integer(), nullable=True))
    if "cost_estimate" not in _column_names("agent_runs"):
        op.add_column('agent_runs', sa.Column('cost_estimate', sa.Float(), nullable=True))
    if "output_version" not in _column_names("agent_runs"):
        op.add_column('agent_runs', sa.Column('output_version', sa.Integer(), nullable=False, server_default=sa.text("1")))
    if "ix_agent_runs_final_memory_id" not in _index_names("agent_runs"):
        op.create_index(op.f('ix_agent_runs_final_memory_id'), 'agent_runs', ['final_memory_id'], unique=False)
    if "ix_agent_runs_id" not in _index_names("agent_runs"):
        op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    if "ix_agent_runs_status" not in _index_names("agent_runs"):
        op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    if "ix_agent_steps_id" not in _index_names("agent_steps"):
        op.create_index(op.f('ix_agent_steps_id'), 'agent_steps', ['id'], unique=False)
    if "ix_agent_steps_run_id" not in _index_names("agent_steps"):
        op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    if "feedback_score" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('feedback_score', sa.Integer(), nullable=False, server_default=sa.text("0")))
    if "reviewer_id" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('reviewer_id', sa.String(length=255), nullable=True))
    if "reviewed_at" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    if "review_reason" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('review_reason', sa.Text(), nullable=True))
    if "source_ids" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('source_ids', sa.Text(), nullable=False, server_default=sa.text("'[]'")))
    if "provider" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('provider', sa.String(length=120), nullable=True))
    if "token_usage" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('token_usage', sa.Integer(), nullable=True))
    if "cost_estimate" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('cost_estimate', sa.Float(), nullable=True))
    if "output_version" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('output_version', sa.Integer(), nullable=False, server_default=sa.text("1")))
    if "workflow_run_id" not in _column_names("ai_memory_brain"):
        op.add_column('ai_memory_brain', sa.Column('workflow_run_id', sa.String(length=80), nullable=True))
    if "ix_ai_memory_brain_category" not in _index_names("ai_memory_brain"):
        op.create_index(op.f('ix_ai_memory_brain_category'), 'ai_memory_brain', ['category'], unique=False)
    if "ix_ai_memory_brain_id" not in _index_names("ai_memory_brain"):
        op.create_index(op.f('ix_ai_memory_brain_id'), 'ai_memory_brain', ['id'], unique=False)
    if "ix_ai_memory_brain_is_public" not in _index_names("ai_memory_brain"):
        op.create_index(op.f('ix_ai_memory_brain_is_public'), 'ai_memory_brain', ['is_public'], unique=False)
    if "ix_ai_memory_brain_post_slug" not in _index_names("ai_memory_brain"):
        op.create_index(op.f('ix_ai_memory_brain_post_slug'), 'ai_memory_brain', ['post_slug'], unique=False)
    if "ix_ai_memory_brain_source_title" not in _index_names("ai_memory_brain"):
        op.create_index(op.f('ix_ai_memory_brain_source_title'), 'ai_memory_brain', ['source_title'], unique=False)
    if "ix_ai_memory_brain_workflow_run_id" not in _index_names("ai_memory_brain"):
        op.create_index(op.f('ix_ai_memory_brain_workflow_run_id'), 'ai_memory_brain', ['workflow_run_id'], unique=False)
    if "ix_analytics_events_created_at" not in _index_names("analytics_events"):
        op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    if "ix_analytics_events_event_type" not in _index_names("analytics_events"):
        op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    if "ix_analytics_events_id" not in _index_names("analytics_events"):
        op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    if "ix_app_settings_key" not in _index_names("app_settings"):
        op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    if "ix_contacts_email" not in _index_names("contacts"):
        op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    if "ix_contacts_id" not in _index_names("contacts"):
        op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    if "ix_dashboard_metrics_id" not in _index_names("dashboard_metrics"):
        op.create_index(op.f('ix_dashboard_metrics_id'), 'dashboard_metrics', ['id'], unique=False)
    if "ix_dashboard_metrics_key" not in _index_names("dashboard_metrics"):
        op.create_index(op.f('ix_dashboard_metrics_key'), 'dashboard_metrics', ['key'], unique=True)
    if "source_version" not in _column_names("document_embeddings"):
        op.add_column('document_embeddings', sa.Column('source_version', sa.Integer(), nullable=False, server_default=sa.text("1")))
    if "indexed_at" not in _column_names("document_embeddings"):
        op.add_column('document_embeddings', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    if "ix_document_embeddings_id" not in _index_names("document_embeddings"):
        op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    if "trust_score" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('trust_score', sa.Float(), nullable=False, server_default=sa.text("0.5")))
    if "content_text" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('content_text', sa.Text(), nullable=False, server_default=sa.text("''")))
    if "content_hash" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('content_hash', sa.String(length=64), nullable=True))
    if "knowledge_status" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('knowledge_status', sa.String(length=40), nullable=False, server_default=sa.text("'new'")))
    if "publication_status" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('publication_status', sa.String(length=40), nullable=False, server_default=sa.text("'unpublished'")))
    if "source_version" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('source_version', sa.Integer(), nullable=False, server_default=sa.text("1")))
    if "indexing_status" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('indexing_status', sa.String(length=40), nullable=False, server_default=sa.text("'not_indexed'")))
    if "indexed_at" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    if "indexing_error" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('indexing_error', sa.Text(), nullable=True))
    if "freshness_score" not in _column_names("intelligence_sources"):
        op.add_column('intelligence_sources', sa.Column('freshness_score', sa.Float(), nullable=False, server_default=sa.text("0.5")))
    if "ix_intelligence_sources_category" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_category'), 'intelligence_sources', ['category'], unique=False)
    if "ix_intelligence_sources_content_hash" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_content_hash'), 'intelligence_sources', ['content_hash'], unique=False)
    if "ix_intelligence_sources_id" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_id'), 'intelligence_sources', ['id'], unique=False)
    if "ix_intelligence_sources_indexing_status" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_indexing_status'), 'intelligence_sources', ['indexing_status'], unique=False)
    if "ix_intelligence_sources_knowledge_status" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_knowledge_status'), 'intelligence_sources', ['knowledge_status'], unique=False)
    if "ix_intelligence_sources_publication_status" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_publication_status'), 'intelligence_sources', ['publication_status'], unique=False)
    if "ix_intelligence_sources_source_type" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_source_type'), 'intelligence_sources', ['source_type'], unique=False)
    if "ix_intelligence_sources_title" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_title'), 'intelligence_sources', ['title'], unique=False)
    if "ix_intelligence_sources_trust_level" not in _index_names("intelligence_sources"):
        op.create_index(op.f('ix_intelligence_sources_trust_level'), 'intelligence_sources', ['trust_level'], unique=False)
    if "ix_posts_category" not in _index_names("posts"):
        op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    if "ix_posts_id" not in _index_names("posts"):
        op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    if "ix_posts_is_published" not in _index_names("posts"):
        op.create_index(op.f('ix_posts_is_published'), 'posts', ['is_published'], unique=False)
    if "ix_posts_title" not in _index_names("posts"):
        op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    if "ix_posts_type" not in _index_names("posts"):
        op.create_index(op.f('ix_posts_type'), 'posts', ['type'], unique=False)
    if "ix_subscribers_email" not in _index_names("subscribers"):
        op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    if "ix_subscribers_id" not in _index_names("subscribers"):
        op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)

    if op.get_bind().dialect.name == "postgresql":
        table_names = ", ".join(f"'{table}'" for table in APPLICATION_TABLES)
        op.execute(
            f"""
            DO $rls$
            DECLARE
                app_table text;
                app_sequence regclass;
                client_role text;
            BEGIN
                FOREACH app_table IN ARRAY ARRAY[{table_names}] LOOP
                    IF to_regclass(format('%I.%I', 'public', app_table)) IS NULL THEN
                        CONTINUE;
                    END IF;

                    EXECUTE format(
                        'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY',
                        'public', app_table
                    );
                    EXECUTE format(
                        'REVOKE ALL PRIVILEGES ON TABLE %I.%I FROM PUBLIC',
                        'public', app_table
                    );

                    FOREACH client_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
                        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = client_role) THEN
                            EXECUTE format(
                                'REVOKE ALL PRIVILEGES ON TABLE %I.%I FROM %I',
                                'public', app_table, client_role
                            );
                        END IF;
                    END LOOP;
                    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
                        EXECUTE format(
                            'GRANT ALL PRIVILEGES ON TABLE %I.%I TO service_role',
                            'public', app_table
                        );
                    END IF;

                    FOR app_sequence IN
                        SELECT sequence_relation.oid::regclass
                        FROM pg_class AS table_relation
                        JOIN pg_namespace AS table_schema
                          ON table_schema.oid = table_relation.relnamespace
                        JOIN pg_depend AS sequence_dependency
                          ON sequence_dependency.refobjid = table_relation.oid
                         AND sequence_dependency.refobjsubid > 0
                         AND sequence_dependency.classid = 'pg_class'::regclass
                         AND sequence_dependency.refclassid = 'pg_class'::regclass
                         AND sequence_dependency.deptype IN ('a', 'i')
                        JOIN pg_class AS sequence_relation
                          ON sequence_relation.oid = sequence_dependency.objid
                         AND sequence_relation.relkind = 'S'
                        WHERE table_schema.nspname = 'public'
                          AND table_relation.relname = app_table
                    LOOP
                        EXECUTE format(
                            'REVOKE ALL PRIVILEGES ON SEQUENCE %s FROM PUBLIC',
                            app_sequence
                        );
                        FOREACH client_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
                            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = client_role) THEN
                                EXECUTE format(
                                    'REVOKE ALL PRIVILEGES ON SEQUENCE %s FROM %I',
                                    app_sequence, client_role
                                );
                            END IF;
                        END LOOP;
                        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
                            EXECUTE format(
                                'GRANT ALL PRIVILEGES ON SEQUENCE %s TO service_role',
                                app_sequence
                            );
                        END IF;
                    END LOOP;
                END LOOP;
            END;
            $rls$;
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Forward-only schema reconciliation avoids dropping application data.
    pass
